// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZaPFS3WR5sB9Uyx-ux2yVHWq2_-u7qgY',
    appId: '1:1012484315207:web:9ba053ef968256dcb9b962',
    messagingSenderId: '1012484315207',
    projectId: 'snakegame-ead3e',
    authDomain: 'snakegame-ead3e.firebaseapp.com',
    storageBucket: 'snakegame-ead3e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0CsHA43fU4S4V28kN8oxhRhxrEStySY',
    appId: '1:1012484315207:android:707d3ea7b0ccb863b9b962',
    messagingSenderId: '1012484315207',
    projectId: 'snakegame-ead3e',
    storageBucket: 'snakegame-ead3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnlhSwNzE2CS1swKqVlZGgcSENRtFGRm0',
    appId: '1:1012484315207:ios:e8233a41e550970cb9b962',
    messagingSenderId: '1012484315207',
    projectId: 'snakegame-ead3e',
    storageBucket: 'snakegame-ead3e.appspot.com',
    iosBundleId: 'com.example.snake',
  );
}
